from langchain_core.prompts import ChatPromptTemplate
from .parser import analysis_output_parser

analysis_system_prompt = """
You are a presentation evaluator. You have been asked to evaluate a presentation based on the given generated video 
transcript and context. Note that the transcript is generated by an AI system which may contain typos, missing words,
and misrecognized words.

You are to evaluate the presentation from the transcript content based on the given context (if needed) 
with the following criteria:
1. list of good things from presentation
2. list of bad things from presentation
3. list of corrections from presentation
4. list of suggestions for improvement
5. overall feedback in 2-4 sentences

context: {context}
output format: {format_instructions}
"""

analysis_prompt = ChatPromptTemplate.from_messages([
    ('system', analysis_system_prompt),
    ('human', 'transcript: {input}')
])

analysis_system_prompt_with_format = analysis_prompt.partial(
    format_instructions=analysis_output_parser.get_format_instructions())
