name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.REGION }}
  APP_NAME: ${{ secrets.APP_NAME }}
  REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
  SERVICE_ACCOUNT_EMAIL: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
  LANGCHAIN_TRACING_V2: ${{ secrets.LANGCHAIN_TRACING_V2 }}
  LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  SQLALCHEMY_DATABASE_URL: ${{ secrets.SQLALCHEMY_DATABASE_URL }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
  GEMINI_AI_KEY: ${{ secrets.GEMINI_AI_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: "auth"
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: "${{ secrets.GCP_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build and tag the docker image
        run: |-
          docker build . --tag $REGION-docker.pkg.dev/$PROJECT_ID/$REGISTRY_NAME/$APP_NAME:latest \
          --build-arg LANGCHAIN_TRACING_V2=$LANGCHAIN_TRACING_V2 \
          --build-arg LANGCHAIN_API_KEY=$LANGCHAIN_API_KEY \
          --build-arg OPENAI_API_KEY=$OPENAI_API_KEY \
          --build-arg SQLALCHEMY_DATABASE_URL=$SQLALCHEMY_DATABASE_URL \
          --build-arg GCP_PROJECT_ID=$GCP_PROJECT_ID \
          --build-arg PINECONE_API_KEY=$PINECONE_API_KEY \
          --build-arg GEMINI_AI_KEY=$GEMINI_AI_KEY

      - name: Push the image to the Google Artifact Registry (GAR)
        run: |-
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REGISTRY_NAME/$APP_NAME:latest

      - name: Deploy
        run: |-
          gcloud run deploy $APP_NAME \
          --region $REGION \
          --image $REGION-docker.pkg.dev/$PROJECT_ID/$REGISTRY_NAME/$APP_NAME:latest \
          --platform "managed" \
          --service-account $SERVICE_ACCOUNT_EMAIL \
          --port 8081 \
          --quiet \
          --allow-unauthenticated
